#! /bin/bash
pdflatex -shell-escape incoherent_prl.tex
pdflatex -shell-escape incoherent_prl.tex
pdflatex -shell-escape incoherent_prl.tex
rm -f *.tex~ incoherent_prl.mtc1 incoherent_prl.aux incoherent_prl.dvi incoherent_prl.lof incoherent_prl.log incoherent_prl.out incoherent_prl.lot incoherent_prl.toc incoherent_prl.brf incoherent_prl.maf incoherent_prl.mtc incoherent_prl.mtc0 incoherent_prl.nlo incoherent_prl.bbl incoherent_prl.blg



pdflatex LZ15969_Hattawy_SummaryOfChanges_May23_2019.tex
rm LZ15969_Hattawy_SummaryOfChanges_May23_2019.aux
rm LZ15969_Hattawy_SummaryOfChanges_May23_2019.log
