#! /bin/bash
pdflatex -shell-escape incoherent_prl.tex
pdflatex -shell-escape incoherent_prl.tex
pdflatex -shell-escape incoherent_prl.tex
pdflatex -shell-escape responsereferee.tex
pdflatex -shell-escape responsereferee.tex
pdflatex -shell-escape responsereferee.tex
rm -f *.tex~ *.mtc1 *.aux *.dvi *.lof *.log *.out *.lot *.toc *.brf *.maf *.mtc *.mtc0 *.nlo *.bbl *.blg

