#! /bin/bash

./Clean

pdflatex final_round_comments.tex
bibtex   final_round_comments
pdflatex final_round_comments.tex
pdflatex final_round_comments.tex

rm final_round_comments.aux final_round_comments.bbl final_round_comments.blg final_round_comments.log final_round_comments.out final_round_comments.maf 
rm final_round_comments.mtc final_round_comments.mtc1 final_round_comments.nlo
rm formatAndDefs.aux
