#! /bin/bash

./Clean

pdflatex 4EG6.tex
bibtex   4EG6
pdflatex 4EG6.tex
pdflatex 4EG6.tex

rm 4EG6.aux 4EG6.bbl 4EG6.blg 4EG6.log 4EG6.out 4EG6.maf 
rm 4EG6.mtc 4EG6.mtc1 4EG6.nlo
rm formatAndDefs.aux
