#! /bin/bash

./Clean

pdflatex 2nd_adhoc_comments.tex
bibtex   2nd_adhoc_comments
pdflatex 2nd_adhoc_comments.tex
pdflatex 2nd_adhoc_comments.tex

rm 2nd_adhoc_comments.aux 2nd_adhoc_comments.bbl 2nd_adhoc_comments.blg 2nd_adhoc_comments.log 2nd_adhoc_comments.out 2nd_adhoc_comments.maf 
rm 2nd_adhoc_comments.mtc* 2nd_adhoc_comments.mtc1 2nd_adhoc_comments.nlo
rm formatAndDefs.aux
